### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by 3togo** [robertogerson/dibr-player#3]
Pls advise how to debug

eli@eli-UX310:build$ ./dibr-player-opencl images/flower04.jpg 
1920x1080
Platform 0: NVIDIA Corporation
Platform found : NVIDIA Corporation

Selected Platform Vendor: NVIDIA Corporation
Number of Devices Found 1
Device -->0 : GeForce 940MX
Device Version -->OpenCL 1.2 CUDA
OpenCL version -->OpenCL C 1.2 
max compute units -->3
Info: Found extension support ‘cl_khr_gl_sharing’!
Found GL Sharing Support!

Reading Kernel File ./convolution.cl

Build Log:

#Decode	Resize	Crop	Filter	DIBR	Show
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /build/opencv-zcaJjh/opencv-3.2.0+dfsg/modules/imgproc/src/imgwarp.cpp, line 3492
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-zcaJjh/opencv-3.2.0+dfsg/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

Aborted (core dumped)
eli@eli-UX310:build$

**Comment by 3togo** [comment]
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/jc/git/dibr-player/build/dibr-player-opencl ../samples/images/flower04.jpg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffcf199700 (LWP 15005)]
1920x1080
[New Thread 0x7fffcd8a7700 (LWP 15009)]
[New Thread 0x7fffcd0a6700 (LWP 15010)]
Error: No available platform found!

Thread 1 "dibr-player-ope" received signal SIGSEGV, Segmentation fault.
0x00007fffffffd6b0 in ?? ()
(gdb)

**Comment by 3togo** [comment]
(gdb) bt
#0  0x00007fffffffd6b0 in  ()
#1  0x00005555555645df in OCLX::getDevice(_cl_platform_id*, unsigned int&, unsigned long, _cl_device_id***) ()
#2  0x000055555556514f in OCLX::init() ()
#3  0x0000555555561ed4 in main ()

**Comment by 3togo** [comment]
fixed by installing beignet-opencl-icd for intel gpu
sudo apt install beignet-opencl-icd
